# CS 316 : Introduction to Deep Learning - Fall 2024
## Lab 01: Numpy Basics
### Instructor: Dr. Abdul Samad
### RA: Sandesh Kumar

# Instructions

1. Make a copy of this notebook on google colab at start of the lab.

2. Please rename your notebook as *Lab_01_aa01234.ipynb* before starting the lab. Notebooks which do not follow appropriate naming convention will not be graded.

3. You have to submit this lab during the lab timings. You are allowed to submit till 11:59 PM on the day of your lab with a 30% penalty. No submissions will be accepted afterwards.

4. Use of AI is strictly prohibited. Anyone caught using Any AI tool during lab or while grading will be immediately reported to OCVS without any further discussion.

5. At the end of the lab, download the notebook (ipynb extension file) and upload it on canvas as a file. Submitting link to notebook or any other file format will not be accepted.

6. Each task has points assigned to it. Total Lab is of 100 points.

7. Use of for loops is strictly prohibited.

8. If there are any theoretical questions, there will be a separate cell given for it after the question. You have to edit it to write your answer there.

9. If you have any questions, please feel free to reach out to the course instructor, RA or TA.

10. Comments are also part of question and are there to help you understand and write the code. Read them carefully.

11. This lab contains testcases. Do not edit them. Run them to check whether your output is correct.

12. Go to settings> AI Assistance> Uncheck all options, save your notebook, refresh the tab and then start your lab.

In [1]:
#Let's import all important libraries first
import numpy as np

# Q1: [6 Points]
Write a command to create a tensor of size 28 x 28 x 30 with all zero values in numpy. Name the variable as tensor

In [ ]:
# Write your Code here
# Start
tensor=np.zeros((28, 28, 30))

# End
print(tensor)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [ ]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

assert tensor.shape == (28, 28, 30)
assert np.all(tensor == 0)
print("Test case passed!")

Test case passed!


# Q2: [8 Points]
Generate the following matrix using numpy. name the variable as matrix.

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1Gnj_JENn95Rnd-eR4gToa4JtU2JZYGe0)

</center>


In [ ]:
# Write your Code here
# Start
matrix= np.diag([1,1,1])
matrix[0][1:]=2
matrix[1][0]=2
matrix[1][2]=2
matrix[2][0:2]=2

# End
print(matrix)

[[1 2 2]
 [2 1 2]
 [2 2 1]]


In [ ]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL
expected_matrix = np.array([[1., 2., 2.],
                            [2., 1., 2.],
                            [2., 2., 1.]])
assert matrix.shape == (3, 3)
assert np.array_equal(matrix, expected_matrix)

print("Test case passed!")

Test case passed!


# Q3: [8 Points]
Chocomo is a chocolate-filled biscuit company. You have a feeling they don't use enough chocolate. So, like any normal human, you phone the production manager and ask how much chocolate they put in, and the manager, like any normal human, tells you that the amount of chocolate in our 100 biscuits pack follows a normal distribution with a mean of 50g and a standard deviation of 9g.



You decide to simulate the Chocomo plant to determine if you are just unlikely or not. Generate 100 samples of biscuits using numpy, with each element in the array indicating how much chocolate each pack contains. Name the variable as chocolates.


In [2]:
# Write your Code here
# Start
chocolates=np.random.normal(50, 9,(100))

# End

print(chocolates)

[45.84579785 62.3192558  55.73465581 60.97693759 55.50073978 40.20164997
 33.07362598 60.07659274 45.08048293 51.89733279 59.29163032 39.58272692
 53.38772524 40.54314634 68.78600481 39.42556477 51.94925556 55.17812109
 57.73809711 55.30688576 52.9152854  41.4960102  49.56515419 50.87014945
 61.87952902 39.71606663 40.20845303 69.6416193  36.57599008 50.0037844
 41.13804092 57.22952246 52.75482579 44.90339935 47.50089859 42.97906643
 50.03876777 51.20907645 46.76055981 35.70928993 53.87192542 63.36888363
 49.62797762 29.51918573 64.33496726 38.53195195 65.53989395 44.58097682
 50.51360644 52.12179366 47.10142855 31.05210252 51.73816973 48.71940819
 54.90798195 66.71803679 61.1478128  38.56042119 41.37485058 45.57573623
 58.83819843 43.56339299 50.95897206 62.84412128 47.27144129 51.14603052
 45.54899433 49.22688408 55.40883991 44.8223712  55.22987254 57.7826775
 51.75117583 41.60702138 41.54386089 35.20683674 43.15793729 40.46136181
 42.10186651 32.85831381 61.10749025 44.01531514 40.5

In [3]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

assert chocolates.shape == (100,)
assert chocolates.dtype == np.float64 or chocolates.dtype == np.float32

print("Test case passed!")

Test case passed!


# Q4: [8 Points]
Fraud at Chocomo Factory:
You look at the data you generated and you saw that what you got was vastly less. You inform this to the Chocomo foundation which conducts an audit and finds out that one of the employees, Augustus Gloop, has been eating the chocolate rather than putting it in the biscuits.

Each employee is supposed to mention how much chocolate they used in each shift. The data is stored in a 2d numpy array chocolate_used. where each row refers to each employee and a column refers to each shift.

You decide to fire Augustus Gloop and set his chocolate_used entries for every shift as 0. Augustus's entry is stored in the last row.

Write code using numpy. Consider you have this array and set augusut's entries to 0.

In [4]:
#DO NOT EDIT THIS CODE
chocolate_used = np.random.rand(5, 10) * 100
original_chocolate_used = np.copy(chocolate_used)

In [5]:
# Write your Code here
# Start
chocolate_used[-1,:]=0

# End

print(chocolate_used)

[[58.3919131  99.81661786 38.95765917 11.26348817  6.77615871  3.72056295
  26.8485457  81.66597587 91.00317154 53.19495112]
 [88.76918754 42.73527919 56.46113094 73.18648295 11.82131725 88.60267888
  73.00731101 31.87250018 21.46061155 48.04222016]
 [ 5.550814   55.73439108 11.52283676 35.03377972 74.02056469 62.06503034
  43.82247013 12.09926531 17.61147418  8.95035428]
 [49.15962666 55.90096104 83.56517362 67.94768391 88.32872328 75.62411581
  27.25483493 81.68480776 93.25967586 47.35743511]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]]


In [6]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

assert np.all(chocolate_used[-1, :] == 0)
assert chocolate_used.shape == original_chocolate_used.shape
assert np.array_equal(chocolate_used[:-1, :], original_chocolate_used[:-1, :])

print("Test case passed!")

Test case passed!


# Q5: [8 Points]
You've grown dissatisfied with the standard scoring system in Pacman and have decided to create your own version of the game. To further enhance this new game, you've formulated a unique scoring system that will be used to assess the performance of an AI you plan to train.



The scoring system is defined by the following formula:


S = 10 x max(T - 30 , 0) + 20D + 50B + 100G
Where:

    S represents the score you achieve.
    T is the time in seconds that you have survived, rounded to the first decimal place.
    D denotes the number of dots you have consumed.
    B stands for the number of berries you have eaten.
    G indicates the number of times you have eaten a ghost.

For example, if I survive for 40 seconds, eat 30 dots, 2 berries, and 5 ghosts, my score will be equal to:


### **Function Description:**

Complete the function pacmanScore in the editor below. The function must return the expected score as an integer.

pacmanScore has the following parameter(s):

    time:  a float64 numpy scalar that tells you the time in seconds that you survived.
    dots: an integer numpy scalar indicating the number of dots you ate.
    berries: an integer numpy scalar indicating the number of berries you ate.
    ghosts: an integer numpy scalar indicating the number of ghosts you ate

    

In [9]:
#
# Complete the 'pacmanScore' function below.
#
# The function is expected to return a np scalar int.
# The function accepts following parameters:
#  1. np scalar float time
#  2. np scalar int dots
#  3. np scalar int berries
#  4. np scalar int ghosts
#

def pacmanScore(time, dots, berries, ghosts):
    # Write your code here. REMEMBER TO RETURN AN INTEGER
    # Start
    s=(10*max(time-30,0))+( 20*dots)+(50*berries)+(100*ghosts)
    return s

    # End



In [10]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

# Test case 1
time1, dots1, berries1, ghosts1 = 40.5, 30, 2, 5
expected_score1 = 10 * max(time1 - 30, 0) + 20 * dots1 + 50 * berries1 + 100 * ghosts1
assert pacmanScore(time1, dots1, berries1, ghosts1) == int(expected_score1), f"Test Case 1 Failed: Input ({time1}, {dots1}, {berries1}, {ghosts1}), Expected: {int(expected_score1)}, Got: {pacmanScore(time1, dots1, berries1, ghosts1)}"

# Test case 2
time2, dots2, berries2, ghosts2 = 25.0, 10, 1, 0
expected_score2 = 10 * max(time2 - 30, 0) + 20 * dots2 + 50 * berries2 + 100 * ghosts2
assert pacmanScore(time2, dots2, berries2, ghosts2) == int(expected_score2), f"Test Case 2 Failed: Input ({time2}, {dots2}, {berries2}, {ghosts2}), Expected: {int(expected_score2)}, Got: {pacmanScore(time2, dots2, berries2, ghosts2)}"

# Test case 3
time3, dots3, berries3, ghosts3 = 60.0, 50, 5, 10
expected_score3 = 10 * max(time3 - 30, 0) + 20 * dots3 + 50 * berries3 + 100 * ghosts3
assert pacmanScore(time3, dots3, berries3, ghosts3) == int(expected_score3), f"Test Case 3 Failed: Input ({time3}, {dots3}, {berries3}, {ghosts3}), Expected: {int(expected_score3)}, Got: {pacmanScore(time3, dots3, berries3, ghosts3)}"

# Test case 4
time4, dots4, berries4, ghosts4 = 30.0, 0, 0, 0
expected_score4 = 10 * max(time4 - 30, 0) + 20 * dots4 + 50 * berries4 + 100 * ghosts4
assert pacmanScore(time4, dots4, berries4, ghosts4) == int(expected_score4), f"Test Case 4 Failed: Input ({time4}, {dots4}, {berries4}, {ghosts4}), Expected: {int(expected_score4)}, Got: {pacmanScore(time4, dots4, berries4, ghosts4)}"

# Test case 5
time5, dots5, berries5, ghosts5 = 35.9, 100, 10, 1
expected_score5 = 10 * max(time5 - 30, 0) + 20 * dots5 + 50 * berries5 + 100 * ghosts5
assert pacmanScore(time5, dots5, berries5, ghosts5) == int(expected_score5), f"Test Case 5 Failed: Input ({time5}, {dots5}, {berries5}, {ghosts5}), Expected: {int(expected_score5)}, Got: {pacmanScore(time5, dots5, berries5, ghosts5)}"

# Test case 6 (edge case: time slightly less than 30)
time6, dots6, berries6, ghosts6 = 29.9, 20, 3, 2
expected_score6 = 10 * max(time6 - 30, 0) + 20 * dots6 + 50 * berries6 + 100 * ghosts6
assert pacmanScore(time6, dots6, berries6, ghosts6) == int(expected_score6), f"Test Case 6 Failed: Input ({time6}, {dots6}, {berries6}, {ghost6}), Expected: {int(expected_score6)}, Got: {pacmanScore(time6, dots6, berries6, ghosts6)}"

# Test case 7 (edge case: time slightly more than 30)
time7, dots7, berries7, ghosts7 = 30.1, 20, 3, 2
expected_score7 = 10 * max(time7 - 30, 0) + 20 * dots7 + 50 * berries7 + 100 * ghosts7
assert pacmanScore(time7, dots7, berries7, ghosts7) == int(expected_score7), f"Test Case 7 Failed: Input ({time7}, {dots7}, {berries7}, {ghost7}), Expected: {int(expected_score7)}, Got: {pacmanScore(time7, dots7, berries7, ghosts7)}"

# Test case 8 (zero for all inputs)
time8, dots8, berries8, ghosts8 = 0.0, 0, 0, 0
expected_score8 = 10 * max(time8 - 30, 0) + 20 * dots8 + 50 * berries8 + 100 * ghosts8
assert pacmanScore(time8, dots8, berries8, ghosts8) == int(expected_score8), f"Test Case 8 Failed: Input ({time8}, {dots8}, {berries8}, {ghost8}), Expected: {int(expected_score8)}, Got: {pacmanScore(time8, dots8, berries8, ghosts8)}"

# Test case 9 (large values)
time9, dots9, berries9, ghosts9 = 100.0, 500, 50, 20
expected_score9 = 10 * max(time9 - 30, 0) + 20 * dots9 + 50 * berries9 + 100 * ghosts9
assert pacmanScore(time9, dots9, berries9, ghosts9) == int(expected_score9), f"Test Case 9 Failed: Input ({time9}, {dots9}, {berries9}, {ghost9}), Expected: {int(expected_score9)}, Got: {pacmanScore(time9, dots9, berries9, ghosts9)}"

# Test case 10 (time exactly 30)
time10, dots10, berries10, ghosts10 = 30.0, 10, 5, 2
expected_score10 = 10 * max(time10 - 30, 0) + 20 * dots10 + 50 * berries10 + 100 * ghosts10
assert pacmanScore(time10, dots10, berries10, ghosts10) == int(expected_score10), f"Test Case 10 Failed: Input ({time10}, {dots10}, {berries10}, {ghost10}), Expected: {int(expected_score10)}, Got: {pacmanScore(time10, dots10, berries10, ghosts10)}"


print("All 10 test cases passed!")

All 10 test cases passed!


# Q6: [10 Points]
After enduring months of stagnation due to the pandemic, you've resolved to reclaim control over your life. This journey involves various aspects such as your body weight, as well as achieving equilibrium between work and personal life. However, embarking on a goal requires a clear understanding of your current position and the direction you intend to move in.

To initiate this process, you recognize the significance of assessing your body mass index (BMI). The BMI serves as a pivotal step in gauging your physical health and can be calculated as follows:

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1u24_SYnaPqVfEYUb95UpdFce5MytbHVQ)

</center>

For example, if you weigh 80kg and are 1.8 m tall, then your BMI is 24.69.

### **Function Description:**

Complete the function calculateBMI in the editor below. The function must return your current BMI as a numpy scalar rounded to 2 decimal places.

calculateBMI has the following parameter(s):
    height:  a numpy scalar with height in cm.
    weight: a numpy scalar with weight in kg.

    

In [27]:
#
# Complete the 'calculateBMI' function below.
#
# The function is expected to return an np scalar float.
# The function accepts following parameters:
#  1. np scalar float height
#  2. np scalar float weight
#

def calculateBMI(height, weight):
    # Write your code here
    # Start
    BMI=weight/(height/100)**2
    return round(BMI,2)


    # End

In [28]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

# Test Case 1: Example from description (80kg, 1.8m -> height=180cm)
height1, weight1 = 180.0, 80.0
expected_bmi1 = 80.0 / (180.0/100)**2
assert np.isclose(calculateBMI(height1, weight1), np.round(expected_bmi1, 2)), f"Test Case 1 Failed: Input ({height1}, {weight1}), Expected: {np.round(expected_bmi1, 2)}, Got: {calculateBMI(height1, weight1)}"

# Test Case 2: Underweight BMI
height2, weight2 = 170.0, 50.0
expected_bmi2 = 50.0 / (170.0/100)**2
assert np.isclose(calculateBMI(height2, weight2), np.round(expected_bmi2, 2)), f"Test Case 2 Failed: Input ({height2}, {weight2}), Expected: {np.round(expected_bmi2, 2)}, Got: {calculateBMI(height2, weight2)}"

# Test Case 3: Overweight BMI
height3, weight3 = 165.0, 75.0
expected_bmi3 = 75.0 / (165.0/100)**2
assert np.isclose(calculateBMI(height3, weight3), np.round(expected_bmi3, 2)), f"Test Case 3 Failed: Input ({height3}, {weight3}), Expected: {np.round(expected_bmi3, 2)}, Got: {calculateBMI(height3, weight3)}"

# Test Case 4: Very short and light
height4, weight4 = 150.0, 45.0
expected_bmi4 = 45.0 / (150.0/100)**2
assert np.isclose(calculateBMI(height4, weight4), np.round(expected_bmi4, 2)), f"Test Case 4 Failed: Input ({height4}, {weight4}), Expected: {np.round(expected_bmi4, 2)}, Got: {calculateBMI(height4, weight4)}"

# Test Case 5: Very tall and heavy
height5, weight5 = 200.0, 120.0
expected_bmi5 = 120.0 / (200.0/100)**2
assert np.isclose(calculateBMI(height5, weight5), np.round(expected_bmi5, 2)), f"Test Case 5 Failed: Input ({height5}, {weight5}), Expected: {np.round(expected_bmi5, 2)}, Got: {calculateBMI(height5, weight5)}"

print("All 5 test cases passed!")

All 5 test cases passed!


# Q7: [12 Points]

Now that you've successfully transformed your life, you've embraced the role of an Orientation Leader. As an OL, you're responsible for engaging individuals in activities that promote their understanding of personal health. Dissatisfied with how Health and Wellness procedures currently rely on Excel for health data analysis, you've taken it upon yourself to introduce a more efficient approach using the power of NumPy.

You're commencing this initiative by focusing on the calculation of Body Mass Index (BMI), much like you did for yourself. However, this time, your goal is to compute BMI values for multiple individuals, enhancing their health awareness. To accomplish this, you're tasked with developing a function that can calculate BMI for a group of people based on their respective weights and heights.

You can compute BMI using the following formula:

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1u24_SYnaPqVfEYUb95UpdFce5MytbHVQ)

</center>

As an example, consider three individuals among the O-kids group: Saqib with a weight of 80 kg and height of 180 cm (resulting in a BMI of 24.69 kg), Fatima weighing 50 kg and standing at 150 cm (leading to a BMI of 22.22 kg), and Bilal weighing 70 kg with a height of 169 cm (resulting in a BMI of 24.51 kg).

### **Function Description**

Complete the function calculateBMI in the editor below. The function must return BMIs rounded to 2 decimal places.

calculateBMI has the following parameter(s):
    heights:  a numpy vector with height in cm.
    weights: a numpy vector with weight in kg.

In [40]:
#
# Complete the 'calculateBMI' function below.
#
# The function is expected to return an np array of floats.
# The function accepts following parameters:
#  1. np vector float heights
#  2. np vector float weights
#

def calculateBMI(heights, weights):
    # Write your code here
    # Start
  BMIs=weights/((heights/100)**2)
  return np.round(BMIs, 2)

    # End

In [41]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

# Test Case 1: Example from description
heights1 = np.array([180.0, 150.0, 169.0])
weights1 = np.array([80.0, 50.0, 70.0])
expected_bmis1 = np.array([24.69, 22.22, 24.51]) # Rounded values from description
calculated_bmis1 = calculateBMI(heights1, weights1)
assert np.allclose(calculated_bmis1, expected_bmis1, atol=0.01), f"Test Case 1 Failed: Input Heights: {heights1}, Weights: {weights1}, Expected: {expected_bmis1}, Got: {calculated_bmis1}"

# Test Case 2: Different set of heights and weights
heights2 = np.array([175.0, 160.0, 190.0, 155.0])
weights2 = np.array([70.0, 55.0, 90.0, 48.0])
expected_bmis2 = np.round(weights2 / (heights2/100)**2, 2)
calculated_bmis2 = calculateBMI(heights2, weights2)
assert np.allclose(calculated_bmis2, expected_bmis2, atol=0.01), f"Test Case 2 Failed: Input Heights: {heights2}, Weights: {weights2}, Expected: {expected_bmis2}, Got: {calculated_bmis2}"

# Test Case 3: Heights and weights with decimals
heights3 = np.array([172.5, 168.0, 185.2])
weights3 = np.array([65.3, 72.1, 88.9])
expected_bmis3 = np.round(weights3 / (heights3/100)**2, 2)
calculated_bmis3 = calculateBMI(heights3, weights3)
assert np.allclose(calculated_bmis3, expected_bmis3, atol=0.01), f"Test Case 3 Failed: Input Heights: {heights3}, Weights: {weights3}, Expected: {expected_bmis3}, Got: {calculated_bmis3}"

# Test Case 4: Single individual (should still work with vectors)
heights4 = np.array([170.0])
weights4 = np.array([60.0])
expected_bmis4 = np.round(weights4 / (heights4/100)**2, 2)
calculated_bmis4 = calculateBMI(heights4, weights4)
assert np.allclose(calculated_bmis4, expected_bmis4, atol=0.01), f"Test Case 4 Failed: Input Heights: {heights4}, Weights: {weights4}, Expected: {expected_bmis4}, Got: {calculated_bmis4}"

# Test Case 5: Multiple individuals with same height and weight
heights5 = np.array([180.0, 180.0, 180.0])
weights5 = np.array([75.0, 75.0, 75.0])
expected_bmis5 = np.round(weights5 / (heights5/100)**2, 2)
calculated_bmis5 = calculateBMI(heights5, weights5)
assert np.allclose(calculated_bmis5, expected_bmis5, atol=0.01), f"Test Case 5 Failed: Input Heights: {heights5}, Weights: {weights5}, Expected: {expected_bmis5}, Got: {calculated_bmis5}"

print("All 5 test cases passed!")

All 5 test cases passed!


#Q8: [14 Points]
The contents of this question are fictional and satirical.

You work at Yautube, a video-sharing network. Since times are bad, you decide to sell out to politicians and billionaires and promote videos that promote their agenda. Several prominent politicians opt to hire you. Your recommendation algorithm provides a score for each video for each user. To promote a video, simply boost the score for that video for each user. You also provide the service of changing the landscape of the entire platform for billionaires by changing the score for each video.


E.g. If you have 2 users and 3 videos, the landscape of your platform is


<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1fsu82DyYa8fvaf82-GIfXnrbEvphgYHP)

</center>

where each row represents a user and each column represents a video.



If a politician asks you to promote the first video by 10 points, the resulting landscape will be

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=10qbS1R5O-fpU3rc52E0TAPeEffrjgJ7t)

</center>


If a billionaire wants to reduce the score of video 1 by 10, keep it constant for 2, and increase video 3 by 20. His order is
<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1yWzASw4hUHVJe8b6-UyfMr2VJ1L7UdVn)

</center>


And hence the resulting landscape will be


<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1JzLsSfLCYG3MaQuW24VjkAU__8a8zuMT)

</center>
Your goal is to implement 2 functions using broadcasting that allow for these changes.


### **Function Descriptions**


Complete the function billionaire_influence in the editor below. The function must return the resulting landscape of your platform.

billionaire_influence has the following parameter(s):

    current_landscape: A 2d numpy array of the current landscape

    demands: A 1d array, signifying how much to change the score of each video by.



Complete the function politician_influence in the editor below. The function must return the resulting landscape of your platform.

politician_influence has the following parameter(s):

    current_landscape: A 2d numpy array of the current landscape

    index: Index of the video they want to promote

    update_amount: Amount to update the score by

In [42]:
def billionaire_influence(current_landscape, demands):
    # Hint: Column Broadcast
    # Write your code here
    # Start
  resulting_landscape = current_landscape+demands
  return resulting_landscape
    # End

def politician_influence(current_landscape, index, update_amount):
    # Hint : Column Broadcast
    # write your code here
    # Start
  current_landscape[:,index]+=update_amount
  return current_landscape

    # End

In [44]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

# Test Case 1: Billionaire influence - positive demands
current_landscape1 = np.array([[10, 20, 30], [40, 50, 60]])
demands1 = np.array([5, -10, 15])
expected_landscape1 = np.array([[15, 10, 45], [45, 40, 75]])
assert np.array_equal(billionaire_influence(current_landscape1.copy(), demands1), expected_landscape1), f"Test Case 1 Failed for billionaire_influence"

# Test Case 2: Billionaire influence - zero demands
current_landscape2 = np.array([[1, 2], [3, 4], [5, 6]])
demands2 = np.array([0, 0])
expected_landscape2 = np.array([[1, 2], [3, 4], [5, 6]])
assert np.array_equal(billionaire_influence(current_landscape2.copy(), demands2), expected_landscape2), f"Test Case 2 Failed for billionaire_influence"

# Test Case 3: Politician influence - update first video
current_landscape3 = np.array([[10, 20, 30], [40, 50, 60]])
index3 = 0
update_amount3 = 10
expected_landscape3 = np.array([[20, 20, 30], [50, 50, 60]])
assert np.array_equal(politician_influence(current_landscape3.copy(), index3, update_amount3), expected_landscape3), f"Test Case 3 Failed for politician_influence"

# Test Case 4: Politician influence - update last video with negative amount
current_landscape4 = np.array([[1, 2], [3, 4], [5, 6]])
index4 = 1
update_amount4 = -5
expected_landscape4 = np.array([[1, -3], [3, -1], [5, 1]])
assert np.array_equal(politician_influence(current_landscape4.copy(), index4, update_amount4), expected_landscape4), f"Test Case 4 Failed for politician_influence"

# Test Case 5: Combined influence (implicitly tested by checking each function separately)
# This test case explicitly combines operations to show the cumulative effect.
# Start with a landscape
landscape5 = np.array([[100, 200], [300, 400]])
# Apply billionaire influence
demands5 = np.array([-50, 100])
landscape5 = billionaire_influence(landscape5, demands5)
# Apply politician influence
index5 = 0
update_amount5 = 75
landscape5 = politician_influence(landscape5, index5, update_amount5)
# Calculate expected landscape after both operations
expected_landscape5_after_billionaire = np.array([[50, 300], [250, 500]])
expected_landscape5_after_politician = np.array([[125, 300], [325, 500]])

assert np.array_equal(landscape5, expected_landscape5_after_politician), f"Test Case 5 Failed for combined influence"
print("All 5 test cases passed!")

All 5 test cases passed!


#Q9: [12 Points]
Matrix Multiplication is extremely powerful. One toy example of matrix multiplication is that you can generate a multiplication table with just 2 matrices. For example, if we want to generate a multiplication table containing the first four multiples of the number of the first three natural numbers , we can multiply  with . The resulting output will be equal to the following:

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1m5OAMtuuzEBApwG3mXW5db9wCg-xKhwg)

</center>

The first row contains 1x1, 1x2, 1x3, and 1x4 and the rest of the rows follow a similar pattern

### **Function Description**

Complete the function getMultiplicationTable in the editor below. The function must return a matrix containing the multiplication table.

getMultiplicationTable has the following parameter(s):
    multiply_with_left:  a numpy vector.
    multiply_with_right: a numpy vector.

In [51]:
#
# Complete the 'getMultiplicationTable' function below.
# The function must return a matrix containing the multiplication table.
# The function accepts following parameters:
#  1. np vector float multiply_with_left
#  2. np vector float multiply_with_right
#

def getMultiplicationTable(multiply_with_left, multiply_with_right):
    # Write your code here
    # Start
  multiply_with_left=multiply_with_left.reshape(multiply_with_left.size,1)
  multiplicationtable=multiply_with_left*multiply_with_right
  return multiplicationtable

    # End

In [52]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

# Test Case 1: Example from description
multiply_with_left1 = np.array([1, 2, 3])
multiply_with_right1 = np.array([1, 2, 3, 4])
expected_table1 = np.array([[1, 2, 3, 4],
                           [2, 4, 6, 8],
                           [3, 6, 9, 12]])
assert np.array_equal(getMultiplicationTable(multiply_with_left1, multiply_with_right1), expected_table1), f"Test Case 1 Failed"

# Test Case 2: Different vectors
multiply_with_left2 = np.array([5, 10])
multiply_with_right2 = np.array([1, 2, 3])
expected_table2 = np.array([[5, 10, 15],
                           [10, 20, 30]])
assert np.array_equal(getMultiplicationTable(multiply_with_left2, multiply_with_right2), expected_table2), f"Test Case 2 Failed"

# Test Case 3: Vectors with decimals
multiply_with_left3 = np.array([1.5, 2.0])
multiply_with_right3 = np.array([2, 3, 4])
expected_table3 = np.array([[3.0, 4.5, 6.0],
                           [4.0, 6.0, 8.0]])
assert np.allclose(getMultiplicationTable(multiply_with_left3, multiply_with_right3), expected_table3), f"Test Case 3 Failed"

# Test Case 4: Single element vectors
multiply_with_left4 = np.array([7])
multiply_with_right4 = np.array([5])
expected_table4 = np.array([[35]])
assert np.array_equal(getMultiplicationTable(multiply_with_left4, multiply_with_right4), expected_table4), f"Test Case 4 Failed"

# Test Case 5: Vector with zero
multiply_with_left5 = np.array([0, 1, 2])
multiply_with_right5 = np.array([10, 20])
expected_table5 = np.array([[0, 0],
                           [10, 20],
                           [20, 40]])
assert np.array_equal(getMultiplicationTable(multiply_with_left5, multiply_with_right5), expected_table5), f"Test Case 5 Failed"

print("All 5 test cases passed!")

All 5 test cases passed!


#Q10: [14 Points]
Later on, in this course,  you will be introduced to the Softmax function which converts numbers into probabilities. The following is the softmax function:

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1UaKdPedtAmcZbLbOsSMHR145JLcjsthq)

</center>

However, the Softmax function can suffer from overflow. This is because (e^32) is greater than 2^32 which is the capacity of an uint32 number.  We can preprocess the input array to prevent overflow from exponentiation and simplify exponentiation.


The preprocessing steps involve subtracting the maximum of each row of y from each element in y.  This will result in the biggest pre-exponentiated value being 0 and avoiding numerical instability.
This preprocessing step will not affect our result as shown below.

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1TnSrfxMjJw2tcu88mbWqmns2D6kCIkgc)

</center>


Your objective in this lab is to preprocess the array rather than implement the softmax function.

Assume you are given a two-dimensional array A which is equal to
<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=1Q4H-yuCzlQU9_fGox6xW3uyiwA6rkbKC)

</center>


After the preprocessing step, the resulting array will be equal to

<center>

![Google Drive Image](https://drive.google.com/uc?export=view&id=19mnBGcKZiHOJ318YGwyRe_PtULQ10gkY)

</center>


In the first row, the maximum value is 5 so after subtracting 5 from each element in the first row you get [-4 -3 0]. Similarly,in the second row, the maximum value is 30 so after subtracting 30 from each element in the second row you get  [-20 -10 0].


### **Function Description:**

In the editor below, complete the function softmax_preprocess. The function must perform the transformation and return the array z.

softmax_preprocess has the following parameter(s):

y:  a 2d numpy array

In [77]:
#
# Complete the 'softmax_preprocess' function below.
#
# The function is expected to return a 2D numpy array.
# The function accepts 2D numpy array y as parameter.
#

def softmax_preprocess(y):
    # Write your code here
    # Start
  ymaxes= np.max(y, axis=1,keepdims=True)
  z=y-ymaxes
  return z

    # End

In [78]:
#THIS IS A TEST CASE
#DO NOT EDIT THIS CELL

# Test case 1: Example from description
y1 = np.array([[1, 2, 5], [10, 20, 30]])
expected_z1 = np.array([[-4, -3, 0], [-20, -10, 0]])
calculated_z1 = softmax_preprocess(y1.copy()) # Use copy to avoid modifying original array in place if the function was written differently
assert np.array_equal(calculated_z1, expected_z1), f"Test Case 1 Failed: Input:\n{y1}\nExpected:\n{expected_z1}\nGot:\n{calculated_z1}"

# Test case 2: Single row
y2 = np.array([[10, 5, 15]])
expected_z2 = np.array([[-5, -10, 0]])
calculated_z2 = softmax_preprocess(y2.copy())
assert np.array_equal(calculated_z2, expected_z2), f"Test Case 2 Failed: Input:\n{y2}\nExpected:\n{expected_z2}\nGot:\n{calculated_z2}"

# Test case 3: Single column
y3 = np.array([[5], [10], [2]])
expected_z3 = np.array([[0], [0], [0]])
calculated_z3 = softmax_preprocess(y3.copy())
assert np.array_equal(calculated_z3, expected_z3), f"Test Case 3 Failed: Input:\n{y3}\nExpected:\n{expected_z3}\nGot:\n{calculated_z3}"

# Test case 4: All elements are the same in a row
y4 = np.array([[7, 7, 7], [2, 2, 2]])
expected_z4 = np.array([[0, 0, 0], [0, 0, 0]])
calculated_z4 = softmax_preprocess(y4.copy())
assert np.array_equal(calculated_z4, expected_z4), f"Test Case 4 Failed: Input:\n{y4}\nExpected:\n{expected_z4}\nGot:\n{calculated_z4}"

# Test case 5: Negative numbers
y5 = np.array([[-1, -5, -2], [-10, -3, -7]])
expected_z5 = np.array([[0, -4, -1], [-7, 0, -4]]) # Max of first row is -1, max of second row is -3
calculated_z5 = softmax_preprocess(y5.copy())
assert np.array_equal(calculated_z5, expected_z5), f"Test Case 5 Failed: Input:\n{y5}\nExpected:\n{expected_z5}\nGot:\n{calculated_z5}"

print("All 5 test cases passed!")

All 5 test cases passed!
